name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: |
          # Ejecutar los tests
          echo "Running tests..."
          go test -v ./...

      - name: Build
        run: |
          # Construir el proyecto
          echo "Building project..."
          go build -v ./...

      - name: Notify Discord on success
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_TEST_WEBHOOK }}
        with:
          args: '✅ **CI Pipeline Succeeded** - Passed all tests and builds for ${{ github.repository }} (${{ github.ref_name }}).'

      - name: Notify Discord on failure
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_TEST_WEBHOOK }}
        with:
          args: '❌ **CI Pipeline Failed** - Issues detected in tests or build for ${{ github.repository }} (${{ github.ref_name }}).'